#! /usr/bin/env python3

import os

def convert_to_markdown(infile, outfile):
    os.system("pandoc -f dokuwiki -t markdown -o " + outfile + " " + infile)


if __name__ == "__main__":
    for root, _, files in os.walk(os.path.curdir):
        txt_files = (file for file in files if file.endswith(".txt"))
        for f in txt_files:
            filename_with_txt = os.path.join(root, f)
            print(filename_with_txt)

            filename_with_txt_md = filename_with_txt+".md"
            convert_to_markdown(filename_with_txt, filename_with_txt_md)

            # Assume first line (heading) is used as page name so use that as title attribute
            with open(filename_with_txt_md) as f:
                title = f.readline().partition(' ')[2]

            basename = filename_with_txt[:-4]
            filename_with_md = basename+".md"
            with open(filename_with_md, "w") as file:
                file.write("---\n")
                file.write("title: "+title)
                file.write("---\n")
                with open(filename_with_txt_md, "r") as original:
                    file.writelines(original.readlines())

            os.remove(filename_with_txt_md)
