#! /bin/bash
echo "Tar'ing the dokuwiki installation on lima"
ssh lima "tar zcvf responsive-dokuwiki.tgz -C /var/www/dokuwiki --exclude=.git --exclude=cache --exclude=vendor --exclude=lib --exclude=inc --exclude=bin --exclude=media --exclude=wiki ."
scp lima:responsive-dokuwiki.tgz .
cd testdata
rm -rf *
tar zxvf ../responsive-dokuwiki.tgz
cd ..
dokuwiki2wikijs testdata
docker cp dokuwiki2wikijs.zip wiki-app:/tmp
echo "Copied to wiki-app:/tmp"
