
# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 21 Aug 2009 15:31:10 +0200
*	@ALL	    	 0
*	@user		 8
*	@sysadmin	16

personal:medarbetarsamtal:*				@ALL	0
personal:medarbetarsamtal:*				@user	0
personal:medarbetarsamtal:*				@admin	0
personal:medarbetarsamtal:anders_bodelius		andbo	2
personal:medarbetarsamtal:anders_bodelius:*		andbo	2
personal:medarbetarsamtal:christoffer_tornroos		chrto	2
personal:medarbetarsamtal:christoffer_tornroos:*	chrto	2
personal:medarbetarsamtal:joakim_sarehag		joasa	2
personal:medarbetarsamtal:joakim_sarehag:*		joasa	2
personal:medarbetarsamtal:roger_magnesved		roger	2
personal:medarbetarsamtal:roger_magnesved:*		roger	2
personal:medarbetarsamtal:thoni2			thoni2	2
personal:medarbetarsamtal:thoni2:*			thoni2	2
personal:rekrytering:kandidater:*			@user	0
