<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: thoni
 * Date: Mon, 25 Jan 2021 13:03:28 +0100
 */

$conf['title'] = 'Responsive Wiki';
$conf['lang'] = 'sv';
$conf['template'] = 'bootstrap3';
$conf['tagline'] = 'Responsive knowledge';
$conf['license'] = '';
$conf['dformat'] = '%Y-%m-%d %H:%M';
$conf['maxtoclevel'] = '2';
$conf['deaccent'] = '0';
$conf['useheading'] = 'navigation';
$conf['useacl'] = 1;
$conf['superuser'] = '@superuser';
$conf['manager'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['subscribers'] = 1;
$conf['mailfrom'] = 'events@responsive.se';
$conf['mailprefix'] = 'Responsive Wiki';
$conf['proxy']['user'] = 'thoni';
$conf['proxy']['pass'] = '<b>V2lraTE2MTg=';
$conf['plugin']['indexmenu']['skip_index'] = '/(sidebar)/';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'optional';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'flatly';
$conf['tpl']['bootstrap3']['showThemeSwitcher'] = 1;
$conf['tpl']['bootstrap3']['leftSidebarGrid'] = 'col-sm-4 col-md-3';
$conf['tpl']['bootstrap3']['inverseNavbar'] = 1;
$conf['tpl']['bootstrap3']['navbarLabels'] = 'login,themes,profile';
$conf['tpl']['bootstrap3']['notifyExtensionsUpdate'] = 1;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
$conf['plugin']['ditaa']['java'] = '/usr/bin/java';
$conf['plugin']['btable']['btable_show_ratio'] = '0';
$conf['plugin']['authldap']['debug'] = '1';
$conf['tpl']['arctic']['left_sidebar_content'] = 'main,user,group,namespace,index';
$conf['tpl']['arctic']['right_sidebar_content'] = 'main,user,group,namespace,index';
$conf['tpl']['dokuwiki']['sidebar'] = 'main,user,group,namespace,index';
